import { SPEC } from "./specs";
import type { Connection, Part, PartRole, SystemId } from "./types";

function p(
  id: string,
  name: string,
  system: SystemId,
  role: PartRole,
  material: string,
  notes: string,
  extra: Partial<Part> = {},
): Part {
  return {
    id,
    name,
    system,
    role,
    qty: extra.qty ?? 1,
    material,
    spec: extra.spec,
    finish: extra.finish,
    weightLb: extra.weightLb,
    notes,
    connections: extra.connections ?? [],
    source: extra.source ?? "SM-100 / POH-172E",
  };
}

function c(to: string, via: Connection["via"], spec: string, note?: string): Connection {
  return { to, via, spec, note };
}

const ribs = (side: "L" | "R"): Part[] =>
  Array.from({ length: SPEC.wing.ribCount }, (_, i) => {
    const n = String(i + 1).padStart(2, "0");
    const station = (i / (SPEC.wing.ribCount - 1)) * (SPEC.wing.semiSpan - 22);
    return p(
      `WING-${side}-RIB-${n}`,
      `${side === "L" ? "Left" : "Right"} wing rib ${i + 1}`,
      "wing",
      "structure",
      "2024-T3 Alclad, formed",
      `Nose-rib / intermediate rib at ${station.toFixed(0)} in from side of body. Lightening holes, spar slots at 25% and 68% chord, flange width ~0.5 in. Inboard ribs carry bladder-tank straps.`,
      {
        spec: `STA ${station.toFixed(0)}`,
        connections: [
          c(`WING-${side}-SPAR-MAIN`, "MS rivet", "AD-4 / AD-5", "Spar web and cap"),
          c(`WING-${side}-SPAR-REAR`, "MS rivet", "AD-4", "Rear spar web"),
          c(`WING-${side}-SKIN-UPPER`, "MS rivet", "AD-4 stagger", "Upper skin"),
          c(`WING-${side}-SKIN-LOWER`, "MS rivet", "AD-4 stagger", "Lower skin"),
        ],
      },
    );
  });

export const PARTS: Part[] = [
  // ——— Fuselage ———
  p("FUS-FIREWALL", "Stainless-steel firewall", "fuselage", "structure", "301 stainless, 0.016–0.020",
    "Station 0 bulkhead. Isolates the O-300-D from the cabin, carries engine-mount fittings, battery box, and through-firewall controls (throttle, mixture, carb heat, primer, tach shaft, fuel, oil pressure).",
    { weightLb: 8.5, spec: "FS 0", connections: [
      c("ENG-MOUNT", "AN bolt", "AN6 / AN7 through fittings", "Four mount feet"),
      c("FUS-LONGERON-L-UP", "MS rivet", "AD-5", "Upper longeron"),
      c("ELE-BATTERY", "clamp", "Battery box on cabin face", "Firewall-aft on 172E"),
    ]}),
  p("FUS-SKIN-CABIN", "Cabin skin and window frames", "fuselage", "skin", "2024-T3 Alclad",
    "Semi-monocoque cabin: skin, stringers, and window frames. 172D-onward Omni-Vision cut-down rear deck. One-piece windshield frame from 172D.",
    { weightLb: 42, finish: "Acrylic enamel, overall white", connections: [
      c("FUS-FIREWALL", "MS rivet", "AD-4/AD-5", "Forward"),
      c("FUS-FLOOR", "MS rivet", "Seat rails / floorboards"),
      c("FUS-DOOR-L", "hinge", "Piano hinge, forward-opening"),
    ]}),
  p("FUS-SKIN-AFT", "Aft-fuselage skin", "fuselage", "skin", "2024-T3 Alclad",
    "Tapered tailcone skin over bulkheads and stringers from baggage bulkhead to stabilizer attach. Dorsal-fin root blends here.",
    { weightLb: 22, connections: [
      c("FUS-SKIN-CABIN", "MS rivet", "Baggage bulkhead lap"),
      c("EMP-HS-SPAR", "AN bolt", "Rear spar attach fittings"),
    ]}),
  p("FUS-BULKHEAD-FS48", "Cabin door-post bulkhead", "fuselage", "structure", "2024-T3 formed channel",
    "Primary cabin former at the front-door post / wing-strut load path into the lower fuselage.",
    { spec: "FS ~48", connections: [c("WING-L-STRUT", "AN bolt", "AN7 strut fitting, L"), c("WING-R-STRUT", "AN bolt", "AN7 strut fitting, R")]}),
  p("FUS-BULKHEAD-FS90", "Rear-spar / seat bulkhead", "fuselage", "structure", "2024-T3 formed",
    "Carries rear-spar carry-through channels above the cabin and rear-seat attach below.",
    { spec: "FS ~90" }),
  p("FUS-BULKHEAD-FS110", "Baggage bulkhead", "fuselage", "structure", "2024-T3",
    "Aft cabin / baggage division with folding hat shelf (172D+). Omni-Vision window frame lands here.",
    { spec: "FS ~110" }),
  p("FUS-LONGERON-L-UP", "Upper left longeron", "fuselage", "structure", "2024-T4 extrusion",
    "Primary longitudinal cap from firewall to tailcone, left.", { qty: 1 }),
  p("FUS-LONGERON-R-UP", "Upper right longeron", "fuselage", "structure", "2024-T4 extrusion",
    "Primary longitudinal cap from firewall to tailcone, right.", { qty: 1 }),
  p("FUS-LONGERON-L-LO", "Lower left longeron", "fuselage", "structure", "2024-T4 extrusion",
    "Carries main-gear spring fitting and strut fitting loads.", { qty: 1 }),
  p("FUS-LONGERON-R-LO", "Lower right longeron", "fuselage", "structure", "2024-T4 extrusion",
    "Carries main-gear spring fitting and strut fitting loads.", { qty: 1 }),
  p("FUS-FLOOR", "Cabin floorboards & seat rails", "fuselage", "structure", "2024-T3 + plywood/aluminum panels",
    "Removable floorboards over control cables, fuel selector, and flap jackscrew. Dual front-seat rails, 172C six-way seats optional.",
    { connections: [c("INT-SEAT-FL", "AN bolt", "Seat pin / rail stop"), c("FUEL-SELECTOR", "screw", "Floor-mounted selector")] }),
  p("FUS-WINDSHIELD", "One-piece windshield", "fuselage", "glass", "Acrylic (stretched)",
    "172D introduced the one-piece wraparound windshield, replacing the earlier two-piece split. Set in rubber/sealant channel.",
    { weightLb: 12, connections: [c("FUS-SKIN-CABIN", "clamp", "Windshield channel + seal")] }),
  p("FUS-WIN-L-FRONT", "Left forward side window", "fuselage", "glass", "Acrylic", "Door window, left. Framed in the door itself.", { connections: [c("FUS-DOOR-L", "clamp", "Window reveal")]}),
  p("FUS-WIN-R-FRONT", "Right forward side window", "fuselage", "glass", "Acrylic", "Door window, right.", { connections: [c("FUS-DOOR-R", "clamp", "Window reveal")]}),
  p("FUS-WIN-L-REAR", "Left rear side window", "fuselage", "glass", "Acrylic", "Fixed rear-seat side glass, left.", {}),
  p("FUS-WIN-R-REAR", "Right rear side window", "fuselage", "glass", "Acrylic", "Fixed rear-seat side glass, right.", {}),
  p("FUS-WIN-OMNI", "Omni-Vision wraparound rear window", "fuselage", "glass", "Acrylic",
    "The 1963 172D signature: cut-down rear deck and wraparound rear glass for aft visibility. Folding hat shelf sits just forward.",
    { connections: [c("FUS-BULKHEAD-FS110", "clamp", "Rear window frame")] }),
  p("FUS-DOOR-L", "Left cabin door", "fuselage", "skin", "2024-T3, formed inner",
    "Forward-hinged cabin door with over-center latch, interior handle, and openable window on many Skyhawks. Step below.",
    { weightLb: 14, connections: [
      c("FUS-SKIN-CABIN", "hinge", "Piano hinge, 3 segments"),
      c("FUS-SKIN-CABIN", "fitting", "Rotary latch + safety pin"),
    ]}),
  p("FUS-DOOR-R", "Right cabin door", "fuselage", "skin", "2024-T3, formed inner",
    "Matching right cabin door. 172 is a true two-door four-seater.",
    { weightLb: 14, connections: [c("FUS-SKIN-CABIN", "hinge", "Piano hinge")] }),
  p("FUS-BAGGAGE-DOOR", "Baggage door (left)", "fuselage", "skin", "2024-T3",
    "Left-side baggage door into the 120 lb compartment aft of the rear seats. Key lock on Skyhawk package.",
    { connections: [c("FUS-SKIN-AFT", "hinge", "Piano hinge + cam latch")] }),
  p("FUS-STEP-L", "Left cabin step", "fuselage", "fairing", "4130 steel, painted",
    "Welded step on the left main-gear spring / fuselage, used to reach the wing walk.",
    { connections: [c("GEAR-MAIN-L-SPRING", "clamp", "Step clamp / bolt")] }),
  p("FUS-STEP-R", "Right cabin step", "fuselage", "fairing", "4130 steel, painted",
    "Matching right step.", { connections: [c("GEAR-MAIN-R-SPRING", "clamp", "Step clamp / bolt")] }),
  p("FUS-CARRY-MAIN", "Main-spar carry-through channels", "fuselage", "structure", "2024 / 7075 channels",
    "Because the spar cannot run through the cabin at head height, left and right main spars meet forged/formed carry-through channels in the roof. Struts take the majority of wing bending.",
    { connections: [
      c("WING-L-SPAR-MAIN", "AN bolt", "Root fittings, multiple AN6/AN7"),
      c("WING-R-SPAR-MAIN", "AN bolt", "Root fittings, multiple AN6/AN7"),
    ]}),

  // ——— Wings ———
  p("WING-L-SPAR-MAIN", "Left main spar", "wing", "structure", "2024-T4 built-up I / extruded caps",
    "Full-span main spar at ~25% chord. Strut attach fitting outboard of the tank. Root bolts to cabin carry-through. Caps take bending; web takes shear.",
    { weightLb: 28, connections: [
      c("FUS-CARRY-MAIN", "AN bolt", "Root attach"),
      c("WING-L-STRUT", "AN bolt", "AN7 / AN8 at strut fitting, ~104 in BL"),
    ]}),
  p("WING-R-SPAR-MAIN", "Right main spar", "wing", "structure", "2024-T4 built-up I / extruded caps",
    "Matching right main spar. 172 spars are not a continuous one-piece carry-through.",
    { weightLb: 28, connections: [c("FUS-CARRY-MAIN", "AN bolt", "Root attach"), c("WING-R-STRUT", "AN bolt", "Strut fitting")] }),
  p("WING-L-SPAR-REAR", "Left rear spar", "wing", "structure", "2024-T3 C-channel",
    "Rear spar at ~68% chord. Hinge beam for flap and aileron. Root ties to rear carry-through above the cabin.",
    { weightLb: 12, connections: [c("WING-L-FLAP", "hinge", "Flap tracks / hinges"), c("WING-L-AILERON", "hinge", "Aileron hinges")] }),
  p("WING-R-SPAR-REAR", "Right rear spar", "wing", "structure", "2024-T3 C-channel",
    "Matching right rear spar.", { weightLb: 12 }),
  p("WING-L-SKIN-UPPER", "Left upper wing skin", "wing", "skin", "2024-T3 Alclad, 0.016–0.025",
    "Upper skin, riveted to ribs and spars. Inboard bay covers the bladder tank. Walkway on the left root (pilot side).",
    { weightLb: 18, finish: "White acrylic enamel" }),
  p("WING-R-SKIN-UPPER", "Right upper wing skin", "wing", "skin", "2024-T3 Alclad, 0.016–0.025",
    "Matching right upper skin. No walkway.", { weightLb: 17 }),
  p("WING-L-SKIN-LOWER", "Left lower wing skin", "wing", "skin", "2024-T3 Alclad",
    "Lower skin with access plates for aileron bellcrank, tank straps, and strut fitting. Pitot and stall-warn live under the left wing.",
    { weightLb: 16 }),
  p("WING-R-SKIN-LOWER", "Right lower wing skin", "wing", "skin", "2024-T3 Alclad",
    "Matching right lower skin.", { weightLb: 16 }),
  p("WING-L-TIP", "Left fiberglass wingtip", "wing", "fairing", "Fiberglass, 172C+",
    "172C introduced fiberglass tips (replacing metal). Houses the red nav lamp. Rounded 1960s contour — not the later tapered tip.",
    { connections: [c("WING-L-SPAR-MAIN", "screw", "Tip rib screws"), c("ELE-NAV-L", "screw", "Nav light")] }),
  p("WING-R-TIP", "Right fiberglass wingtip", "wing", "fairing", "Fiberglass, 172C+",
    "Green nav lamp in the right tip.", { connections: [c("ELE-NAV-R", "screw", "Nav light")] }),
  p("WING-L-FLAP", "Left slotted flap", "wing", "skin", "2024-T3, ribbed",
    "Inboard slotted/Fowler-style 'Para-Lift' flap. 172C+ travel 0–10–20–40°. 172E is still the manual Johnson-bar / jackscrew system (electric arrives on 172F, 1965).",
    { weightLb: 9, connections: [
      c("WING-L-SPAR-REAR", "hinge", "Flap tracks"),
      c("CTL-FLAP-JACKSCREW", "pushrod", "Flap pushrod / bellcrank"),
    ]}),
  p("WING-R-FLAP", "Right slotted flap", "wing", "skin", "2024-T3, ribbed",
    "Matching right flap, mechanically slaved to the left via torque tube.", { weightLb: 9 }),
  p("WING-L-AILERON", "Left Frise aileron", "wing", "skin", "2024-T3",
    "Frise-type aileron: leading edge projects into the airstream when the aileron goes up, adding drag to help with adverse yaw. Differential throw (more up than down).",
    { weightLb: 7, connections: [
      c("WING-L-SPAR-REAR", "hinge", "Three hinges"),
      c("CTL-BELLCRANK-AIL-L", "pushrod", "Aileron pushrod"),
    ]}),
  p("WING-R-AILERON", "Right Frise aileron", "wing", "skin", "2024-T3",
    "Matching right aileron, cable-linked through the cabin to the yokes.", { weightLb: 7 }),
  p("WING-L-STRUT", "Left wing strut", "wing", "structure", "Streamlined 2024 / 6061 extrusion",
    "Single main lift strut, airfoil section. Lower AN7 at fuselage fitting (near gear), upper AN7/AN8 at spar fitting ~104 in BL. Jury strut braces the main strut in compression.",
    { weightLb: 11, connections: [
      c("FUS-BULKHEAD-FS48", "AN bolt", "AN7 lower, castellated + cotter"),
      c("WING-L-SPAR-MAIN", "AN bolt", "Upper strut fitting"),
      c("WING-L-JURY", "AN bolt", "Jury clamp / fitting"),
    ]}),
  p("WING-R-STRUT", "Right wing strut", "wing", "structure", "Streamlined 2024 / 6061 extrusion",
    "Matching right lift strut.", { weightLb: 11 }),
  p("WING-L-JURY", "Left jury strut", "wing", "structure", "Streamlined aluminum tube",
    "Short brace from mid-main-strut to the wing undersurface inboard of the main attach, preventing main-strut buckling.",
    { connections: [c("WING-L-STRUT", "AN bolt", "Mid-strut clamp"), c("WING-L-SPAR-MAIN", "AN bolt", "Wing fitting")] }),
  p("WING-R-JURY", "Right jury strut", "wing", "structure", "Streamlined aluminum tube",
    "Matching right jury strut.", {}),
  p("WING-L-FAIRING-ROOT", "Left wing-root fairing", "wing", "fairing", "Fiberglass / aluminum",
    "Closes the wing-to-cabin joint and hides the spar bolts and fuel lines.", {}),
  p("WING-R-FAIRING-ROOT", "Right wing-root fairing", "wing", "fairing", "Fiberglass / aluminum",
    "Matching right root fairing.", {}),
  ...ribs("L"),
  ...ribs("R"),

  // ——— Empennage ———
  p("EMP-DORSAL", "Dorsal fin", "empennage", "skin", "2024-T3",
    "Fillet from cabin roof / tailcone into the vertical stabilizer. Improves yaw stability and fairing.",
    { connections: [c("EMP-VS-SPAR", "MS rivet", "VS root"), c("FUS-SKIN-AFT", "MS rivet", "Tailcone")] }),
  p("EMP-VS-SPAR", "Vertical-stabilizer spar", "empennage", "structure", "2024-T4",
    "Swept (from 172A, 1960) VS front and rear spars. Rear spar carries the rudder hinges.",
    { connections: [c("FUS-SKIN-AFT", "AN bolt", "VS-to-fuselage fittings"), c("EMP-RUDDER", "hinge", "Three rudder hinges")] }),
  p("EMP-VS-SKIN", "Vertical-stabilizer skin", "empennage", "skin", "2024-T3 Alclad",
    "Swept fin skin, 172A-onward. 172E still has the earlier cap (redesigned on 172K).",
    { finish: "White with red fin leading stripe" }),
  p("EMP-RUDDER", "Rudder", "empennage", "skin", "2024-T3",
    "All-metal rudder, cable-driven from the pedals. Ground-adjustable or trim-tab trailing edge. White tail nav light in the trailing-edge cap on many ships.",
    { connections: [
      c("EMP-VS-SPAR", "hinge", "Three hinges + bearing"),
      c("CTL-CABLE-RUD", "cable", "Rudder horns, AN23 clevis"),
      c("ELE-NAV-TAIL", "screw", "Aft nav light"),
    ]}),
  p("EMP-RUDDER-TAB", "Rudder trim / anti-servo tab", "empennage", "skin", "2024-T3",
    "Small trailing-edge tab, typically ground-adjustable on this era 172 (cockpit rudder trim is not standard).", {}),
  p("EMP-HS-SPAR", "Horizontal-stabilizer spar", "empennage", "structure", "2024-T4",
    "172D increased HS span. Front and rear spars bolt to the tailcone. Rear spar is the elevator hinge beam.",
    { connections: [c("FUS-SKIN-AFT", "AN bolt", "Four primary attach bolts")] }),
  p("EMP-HS-SKIN", "Horizontal-stabilizer skin", "empennage", "skin", "2024-T3 Alclad",
    "Fixed stabilizer, constant-ish chord, NACA 00xx-family section. Tips rounded.", {}),
  p("EMP-ELEV-L", "Left elevator", "empennage", "skin", "2024-T3",
    "Left elevator, mass-balanced, cable-driven. Torque tube joins left and right.",
    { connections: [c("EMP-HS-SPAR", "hinge", "Elevator hinges"), c("CTL-CABLE-ELEV", "cable", "Elevator horn")] }),
  p("EMP-ELEV-R", "Right elevator", "empennage", "skin", "2024-T3",
    "Right elevator carries the trim tab on this era 172.",
    { connections: [c("EMP-TRIM-TAB", "hinge", "Trim-tab hinges")] }),
  p("EMP-TRIM-TAB", "Elevator trim tab", "empennage", "skin", "2024-T3",
    "Cockpit trim wheel drives a jackscrew in the right elevator via cables, moving this tab. Nose-up / nose-down trim.",
    { connections: [c("CTL-TRIM-JACK", "pushrod", "Tab pushrod")] }),

  // ——— Gear ———
  p("GEAR-MAIN-L-SPRING", "Left main spring-steel leg", "landing-gear", "structure", "6150 / 5160 spring steel",
    "Cessna Land-O-Matic: a single tapered spring-steel leaf, no oleo. Clamped to a fuselage forging. Absorbs landing loads in bending.",
    { weightLb: 18, connections: [
      c("FUS-LONGERON-L-LO", "AN bolt", "Gear forging, multiple AN8/AN10"),
      c("GEAR-MAIN-L-AXLE", "AN bolt", "Axle through spring eye"),
    ]}),
  p("GEAR-MAIN-R-SPRING", "Right main spring-steel leg", "landing-gear", "structure", "6150 / 5160 spring steel",
    "Matching right main spring.", { weightLb: 18 }),
  p("GEAR-MAIN-L-AXLE", "Left main axle & brake", "landing-gear", "system", "4130 steel + Cleveland",
    "Cleveland (or Goodyear on some early) single-disc hydraulic brake, 6.00-6 wheel. Toe brakes on the rudder pedals.",
    { connections: [c("GEAR-MAIN-L-WHEEL", "bearing", "Tapered roller"), c("CTL-PEDAL-L", "hose", "Brake line")] }),
  p("GEAR-MAIN-R-AXLE", "Right main axle & brake", "landing-gear", "system", "4130 steel + Cleveland",
    "Matching right brake. Differential braking steers beyond the nose-gear stop.", {}),
  p("GEAR-MAIN-L-WHEEL", "Left main wheel & tire", "landing-gear", "system", "Aluminum wheel, 6.00-6 tire",
    "6.00-6 four- or six-ply tube-type tire, typical 29 psi. Optional wheel fairing on Skyhawk.", { weightLb: 12 }),
  p("GEAR-MAIN-R-WHEEL", "Right main wheel & tire", "landing-gear", "system", "Aluminum wheel, 6.00-6 tire",
    "Matching right main wheel.", { weightLb: 12 }),
  p("GEAR-MAIN-L-FAIRING", "Left main wheel fairing", "landing-gear", "fairing", "Fiberglass",
    "Skyhawk-package 'speed fairing'. 172C redesigned the shape. Splits for wheel/tire service.", {}),
  p("GEAR-MAIN-R-FAIRING", "Right main wheel fairing", "landing-gear", "fairing", "Fiberglass",
    "Matching right speed fairing.", {}),
  p("GEAR-NOSE-STRUT", "Nose oleo strut", "landing-gear", "structure", "Steel tube, air-oil oleo",
    "Steerable nose gear, air-oil shock. Linked to the rudder pedals (~10° either side); more with differential brake. 172B shortened the legs; 172H later shortened the oleo further.",
    { weightLb: 16, connections: [
      c("FUS-FIREWALL", "AN bolt", "Engine-mount / firewall forging"),
      c("CTL-PEDAL-L", "pushrod", "Steering bungees / rods"),
    ]}),
  p("GEAR-NOSE-FORK", "Nose fork & shimmy damper", "landing-gear", "structure", "Forged aluminum / steel",
    "Fork carries the 5.00-5 wheel. Hydraulic shimmy damper is mandatory — a loose damper is a classic 172 squawk.",
    { connections: [c("GEAR-NOSE-WHEEL", "bearing", "Axle"), c("GEAR-NOSE-STRUT", "bearing", "Torque links")] }),
  p("GEAR-NOSE-WHEEL", "Nose wheel & tire", "landing-gear", "system", "Aluminum wheel, 5.00-5 tire",
    "5.00-5 nose tire, typically 26 psi. Fairing optional on Skyhawk.", { weightLb: 8 }),
  p("GEAR-NOSE-FAIRING", "Nose wheel fairing", "landing-gear", "fairing", "Fiberglass",
    "Skyhawk nose speed fairing, split around the fork.", {}),

  // ——— Powerplant ———
  p("ENG-CRANKCASE", "O-300-D crankcase", "powerplant", "structure", "Aluminum casting, two-piece",
    "Horizontally-opposed six. Upper and lower case halves sandwich the crankshaft. Four engine-mount lugs, prop flange forward, accessory case aft.",
    { weightLb: 62, source: "O300-OH", connections: [
      c("ENG-MOUNT", "Lord mount", "Four dynafocal-style rubber isolators"),
      c("ENG-SUMP", "AN bolt", "Oil-sump studs"),
    ]}),
  p("ENG-CYL-1", "Cylinder 1 (right front)", "powerplant", "structure", "Steel barrel, aluminum head",
    "Continental numbering: odd cylinders on the right as seen from the rear. Barrel screwed/shrunk into the head; two valves, rocker box, cooling fins.",
    { weightLb: 14, source: "O300-OH", qty: 1 }),
  p("ENG-CYL-2", "Cylinder 2 (left front)", "powerplant", "structure", "Steel barrel, aluminum head",
    "Even cylinders on the left. Pushrod tubes from the crankcase.", { weightLb: 14, source: "O300-OH" }),
  p("ENG-CYL-3", "Cylinder 3 (right mid)", "powerplant", "structure", "Steel barrel, aluminum head",
    "Right bank, middle.", { weightLb: 14, source: "O300-OH" }),
  p("ENG-CYL-4", "Cylinder 4 (left mid)", "powerplant", "structure", "Steel barrel, aluminum head",
    "Left bank, middle.", { weightLb: 14, source: "O300-OH" }),
  p("ENG-CYL-5", "Cylinder 5 (right rear)", "powerplant", "structure", "Steel barrel, aluminum head",
    "Right bank, rear — closest to the accessory case.", { weightLb: 14, source: "O300-OH" }),
  p("ENG-CYL-6", "Cylinder 6 (left rear)", "powerplant", "structure", "Steel barrel, aluminum head",
    "Left bank, rear.", { weightLb: 14, source: "O300-OH" }),
  p("ENG-SUMP", "Oil sump (wet)", "powerplant", "system", "Aluminum casting",
    "Wet sump, 8 US quarts. Pickup, suction screen, and oil-temp bulb. Gravity drain on the bottom.",
    { weightLb: 8, source: "O300-OH" }),
  p("ENG-CARB", "Marvel-Schebler MA-3SPA carburetor", "powerplant", "system", "Aluminum body, updraft",
    "Updraft carb under the oil sump. Mixture, throttle, and carb-heat box. Carb ice is a 172 training classic — heat muff on the exhaust feeds the air box.",
    { weightLb: 6, source: "O300-OH", connections: [
      c("ENG-SUMP", "AN bolt", "Carb studs through spacer"),
      c("ENG-HEAT-MUFF", "hose", "Carb-heat scat tube"),
      c("CTL-THROTTLE", "cable", "Throttle arm"),
      c("CTL-MIXTURE", "cable", "Mixture arm"),
    ]}),
  p("ENG-MAG-L", "Left magneto", "powerplant", "system", "Bendix / Slick",
    "Impulse-coupled magneto, independent of the ship's 12 V system. Left mag typically fires the lower plugs.",
    { source: "O300-OH", connections: [c("ENG-CRANKCASE", "clamp", "Accessory-case pad")] }),
  p("ENG-MAG-R", "Right magneto", "powerplant", "system", "Bendix / Slick",
    "Right mag, upper plugs. Dual ignition is the certification requirement — mags are not 'backup,' they are primary.",
    { source: "O300-OH" }),
  p("ENG-STARTER", "Starter (12 V)", "powerplant", "system", "Prestolite / Delco class",
    "Bendix-drive starter on the accessory case. 172C replaced the earlier pull-handle starter with a key start.",
    { weightLb: 16, source: "O300-OH" }),
  p("ENG-GENERATOR", "Generator (12 V)", "powerplant", "system", "Delco-Remy class, ~20–35 A",
    "172E still uses a generator. The 60 A alternator arrives on the 172H (1967). Belt or gear driven on the accessory case.",
    { weightLb: 12, source: "O300-OH", connections: [c("ELE-BATTERY", "cable", "Ammeter / master / battery")] }),
  p("ENG-OIL-COOLER", "Oil cooler", "powerplant", "system", "Aluminum radiator",
    "Air-blast oil cooler in the rear baffle, regulated by a thermostatic valve on many O-300 installs.",
    { source: "O300-OH" }),
  p("ENG-EXHAUST-L", "Left exhaust collector", "powerplant", "system", "321 stainless",
    "Collector from cylinders 2-4-6 into the muffler / heat exchanger under the engine.",
    { connections: [c("ENG-HEAT-MUFF", "clamp", "Muffler inlet")] }),
  p("ENG-EXHAUST-R", "Right exhaust collector", "powerplant", "system", "321 stainless",
    "Collector from cylinders 1-3-5.", {}),
  p("ENG-HEAT-MUFF", "Muffler & cabin-heat muff", "powerplant", "system", "Stainless shroud",
    "Exhaust muffler with a shroud that picks up cabin heat and carb heat. A cracked muff is a carbon-monoxide risk — annual inspection item.",
    { connections: [c("INT-SEAT-FL", "hose", "Cabin-heat scat through firewall")] }),
  p("ENG-MOUNT", "Steel-tube engine mount", "powerplant", "structure", "4130 welded tube",
    "Welded 4130 mount, four Lord isolators at the case, bolted to the firewall. 172B lengthened the mount 3 in and reshaped the cowl.",
    { weightLb: 14, connections: [c("FUS-FIREWALL", "AN bolt", "Firewall fittings, AN6/AN7")] }),
  p("ENG-BAFFLE", "Cooling baffles", "powerplant", "system", "Aluminum sheet + seals",
    "Pressure baffles force cooling air down through the cylinder fins and out the cowl flaps / cowl exit. Missing seals run CHT up fast.",
    { source: "O300-OH" }),

  // ——— Prop ———
  p("PROP-HUB", "Propeller hub", "propeller", "structure", "Forged aluminum",
    "McCauley fixed-pitch hub, splined/bolted to the O-300 crankshaft flange. 1/2 in prop bolts, torqued and safetied.",
    { source: "MCAULEY", connections: [c("ENG-CRANKCASE", "AN bolt", "Prop flange bolts, 6×")] }),
  p("PROP-BLADE-1", "Propeller blade (1)", "propeller", "skin", "Aluminum alloy, shot-peened",
    "76 in diameter class, ~58 in pitch. Clark-Y-ish section, washout toward the tip. Tracking and nicks are 100-hour items.",
    { source: "MCAULEY" }),
  p("PROP-BLADE-2", "Propeller blade (2)", "propeller", "skin", "Aluminum alloy, shot-peened",
    "Second blade, 180° from blade 1.", { source: "MCAULEY" }),
  p("PROP-SPINNER", "Pointed spinner", "propeller", "fairing", "Aluminum",
    "172B introduced the pointed spinner; 172G later made it longer. Backplate + forward dome, screws around the equator.",
    { connections: [c("PROP-HUB", "screw", "Spinner screws + backplate")] }),

  // ——— Controls ———
  p("CTL-YOKE-L", "Left control yoke", "flight-controls", "system", "Steel tube + plastic/metal wheel",
    "Dual yokes, not a throw-over. Fore-aft = elevator, rotate = aileron. Mic button on the left horn on radio-equipped Skyhawks.",
    { connections: [c("CTL-COLUMN", "clamp", "Yoke shaft"), c("CTL-CABLE-AIL", "cable", "Aileron chains/cables")] }),
  p("CTL-YOKE-R", "Right control yoke", "flight-controls", "system", "Steel tube + plastic/metal wheel",
    "Copilot yoke, mechanically slaved.", {}),
  p("CTL-COLUMN", "Control-column torque tube", "flight-controls", "structure", "Steel tube",
    "Behind the panel: aileron chain/cable sector and elevator push/cable attach.", {}),
  p("CTL-PEDAL-L", "Left rudder pedals (with toe brakes)", "flight-controls", "system", "Steel + pads",
    "172D new rudder/brake pedals. Direct cables to the rudder horn; hydraulic master cylinders for the mains; bungees to the nose gear.",
    { connections: [
      c("CTL-CABLE-RUD", "cable", "Rudder cables, 1/8 in extra-flex"),
      c("GEAR-MAIN-L-AXLE", "hose", "Left brake"),
      c("GEAR-NOSE-STRUT", "pushrod", "Steering bungees"),
    ]}),
  p("CTL-PEDAL-R", "Right rudder pedals (with toe brakes)", "flight-controls", "system", "Steel + pads",
    "Copilot pedals, slaved. Independent master cylinders so either pilot can brake.", {}),
  p("CTL-CABLE-AIL", "Aileron cable circuit", "flight-controls", "system", "1/8 extra-flex, AN terminals",
    "Yokes → chains/cables → turnbuckles in the cabin roof → wing-root pulleys → bellcranks → pushrods to the Frise ailerons. Carry-through interconnect.",
    { connections: [c("CTL-BELLCRANK-AIL-L", "cable", "Left wing"), c("CTL-BELLCRANK-AIL-R", "cable", "Right wing")] }),
  p("CTL-CABLE-ELEV", "Elevator cable circuit", "flight-controls", "system", "1/8 extra-flex",
    "Column → under-floor cables → tailcone pulleys → elevator horn. Tension per 100-series rigging chart.",
    { connections: [c("EMP-ELEV-L", "cable", "Elevator horn")] }),
  p("CTL-CABLE-RUD", "Rudder cable circuit", "flight-controls", "system", "1/8 extra-flex",
    "Pedals → under-floor → tailcone → rudder horns. Check fairleads at bulkheads.",
    { connections: [c("EMP-RUDDER", "cable", "Rudder horns")] }),
  p("CTL-BELLCRANK-AIL-L", "Left aileron bellcrank", "flight-controls", "system", "Aluminum / steel",
    "In the left wing, converts cable travel to aileron pushrod. Inspection plate on the lower skin.", {}),
  p("CTL-BELLCRANK-AIL-R", "Right aileron bellcrank", "flight-controls", "system", "Aluminum / steel",
    "Matching right bellcrank.", {}),
  p("CTL-FLAP-LEVER", "Manual flap lever (Johnson bar)", "flight-controls", "system", "Steel, between seats",
    "172E still uses the floor-mounted manual lever and jackscrew — not the 172F electric motor. Detents at 0 / 10 / 20 / 40°.",
    { connections: [c("CTL-FLAP-JACKSCREW", "fitting", "Lever to jackscrew")] }),
  p("CTL-FLAP-JACKSCREW", "Flap jackscrew & torque tube", "flight-controls", "structure", "Steel jackscrew",
    "Converts lever travel into symmetric flap deflection via a torque tube across the cabin into both wings.",
    { connections: [c("WING-L-FLAP", "pushrod", "Left"), c("WING-R-FLAP", "pushrod", "Right")] }),
  p("CTL-TRIM-WHEEL", "Elevator trim wheel", "flight-controls", "system", "Aluminum wheel, cabin wall",
    "Typically on the center pedestal / lower panel. Cables to the tail-mounted trim jackscrew.",
    { connections: [c("CTL-TRIM-JACK", "cable", "Trim cables")] }),
  p("CTL-TRIM-JACK", "Trim-tab jackscrew", "flight-controls", "system", "Steel jackscrew in right elevator",
    "Moves the elevator trim tab. Check free-play at annual.", { connections: [c("EMP-TRIM-TAB", "pushrod", "Tab")] }),
  p("CTL-THROTTLE", "Throttle (black knob)", "flight-controls", "system", "Vernier / plunger, cable",
    "Black knob, quadrant or plunger on the panel. Cable through the firewall to the MA-3SPA throttle arm.",
    { connections: [c("ENG-CARB", "cable", "Throttle arm")] }),
  p("CTL-MIXTURE", "Mixture (red knob)", "flight-controls", "system", "Plunger, cable",
    "Red mixture. Idle-cutoff at full lean — the 172 shutdown procedure.", { connections: [c("ENG-CARB", "cable", "Mixture arm")] }),
  p("CTL-CARBHEAT", "Carburetor heat (clear/wood knob)", "flight-controls", "system", "Plunger, cable",
    "Selects filtered ram air vs. heated air from the exhaust muff. No filter on hot air — don't use on dusty ground.",
    { connections: [c("ENG-CARB", "cable", "Heat-box arm")] }),

  // ——— Fuel ———
  p("FUEL-TANK-L", "Left wing bladder tank (21 gal)", "fuel", "system", "Goodyear / Uniroyal bladder",
    "21 US gal bladder in the inboard left wing (total 42, ~39 usable). Gravity feed — the high wing is the pump. Vented, with a visual quantity sender.",
    { weightLb: 8, connections: [
      c("FUEL-SELECTOR", "hose", "Left tank line, aluminum + rubber"),
      c("FUEL-CAP-L", "clamp", "Filler neck"),
    ]}),
  p("FUEL-TANK-R", "Right wing bladder tank (21 gal)", "fuel", "system", "Goodyear / Uniroyal bladder",
    "Matching 21 gal right bladder. Selector: LEFT / RIGHT / BOTH / OFF. BOTH is the normal takeoff/landing position.",
    { weightLb: 8 }),
  p("FUEL-CAP-L", "Left fuel cap", "fuel", "system", "Aluminum, vented",
    "Overwing filler. Vents must be clear — a clogged vent will collapse a bladder.", {}),
  p("FUEL-CAP-R", "Right fuel cap", "fuel", "system", "Aluminum, vented",
    "Matching right cap.", {}),
  p("FUEL-SELECTOR", "Fuel selector valve", "fuel", "system", "Aluminum valve, floor",
    "Four-position valve on the cabin floor between the pilots. BOTH / LEFT / RIGHT / OFF. A worn valve is a fuel-starvation item.",
    { connections: [c("FUEL-STRAINER", "hose", "Selector to gascolator")] }),
  p("FUEL-STRAINER", "Fuel strainer (gascolator)", "fuel", "system", "Aluminum bowl, firewall",
    "Lowest point of the fuel system, on the firewall. Drain before flight — 172s collect water here. Screen inside.",
    { connections: [c("ENG-CARB", "hose", "Strainer to carb"), c("FUEL-PRIMER", "hose", "Primer takeoff")] }),
  p("FUEL-PRIMER", "Engine primer", "fuel", "system", "Brass plunger on panel",
    "Draws from the strainer and injects into the intake. 2–4 shots on a cold O-300; none when hot.",
    { connections: [c("ENG-CYL-1", "hose", "Primer lines to cylinders")] }),
  p("FUEL-VENT", "Fuel vents & interconnect", "fuel", "system", "Aluminum tube",
    "Under-wing vents plus tank interconnect. BOTH selected equalizes the tanks in flight, slowly.", {}),

  // ——— Electrical ———
  p("ELE-BATTERY", "Battery (12 V)", "electrical", "system", "Lead-acid, ~12 V 25–35 Ah",
    "Firewall-aft battery box on the 172E. Master solenoid nearby. 24 V does not arrive until much later 172s.",
    { weightLb: 27, connections: [c("ELE-MASTER", "cable", "Battery cable"), c("FUS-FIREWALL", "clamp", "Battery box")] }),
  p("ELE-MASTER", "Master solenoid & split rocker", "electrical", "system", "Solenoid + switch",
    "BAT / ALT (here GEN) split rocker on the left panel. Pulling the master kills the ship's bus; mags are independent.", {}),
  p("ELE-BREAKERS", "Circuit-breaker panel", "electrical", "system", "Klixon-type breakers",
    "172E replaced glass fuses with circuit breakers — a defining 1964 change. Grouped on the lower panel.",
    { source: "POH-172E" }),
  p("ELE-NAV-L", "Left nav light (red)", "electrical", "system", "A-1815 / Grimes class",
    "Red, in the left fiberglass tip. 12 V.", { connections: [c("WING-L-TIP", "screw", "Tip lamp")] }),
  p("ELE-NAV-R", "Right nav light (green)", "electrical", "system", "A-1815 / Grimes class",
    "Green, right tip.", {}),
  p("ELE-NAV-TAIL", "Tail nav light (white)", "electrical", "system", "A-1815 class",
    "White, rudder trailing-edge cap.", {}),
  p("ELE-LANDING", "Landing light (left wing)", "electrical", "system", "Sealed beam, leading edge",
    "Landing lamp in the left wing leading edge on this era 172 (later models moved it to the cowl).",
    { connections: [c("WING-L-SKIN-UPPER", "clamp", "LE cutout")] }),
  p("ELE-BEACON", "Anti-collision beacon", "electrical", "system", "Rotating / flashing red",
    "Fin-tip or dorsal beacon. 172H standardized a rotating beacon over the earlier flasher.", {}),
  p("ELE-STALL", "Stall-warning vane", "electrical", "system", "Electric horn + vane",
    "Leading-edge vane inboard left wing. 172H later went pneumatic. Horn behind the panel.", {}),
  p("ELE-PITOT", "Pitot tube", "electrical", "system", "Heated or unheated brass/aluminum",
    "Under the left wing. Static ports on the fuselage sides. Feeds the ASI, VSI, and altimeter.",
    { connections: [c("INS-ASI", "hose", "Pitot line")] }),

  // ——— Instruments ———
  p("INS-PANEL", "Instrument panel (172E layout)", "instruments", "structure", "Aluminum, shock-mounted",
    "172E redesigned the panel: center-stack avionics and the new breaker field. Not yet the 172I 'T' arrangement. Shock mounts for the gyros.",
    { source: "POH-172E" }),
  p("INS-ASI", "Airspeed indicator", "instruments", "system", "Pitot-static, 3-1/8 in",
    "Statute-mph dial on 1964 ships (knots come later). Color arcs per TCDS.", { connections: [c("ELE-PITOT", "hose", "Pitot/static")] }),
  p("INS-AI", "Attitude indicator", "instruments", "system", "Vacuum gyro",
    "Artificial horizon, vacuum from the engine-driven pump. Cage knob on some units.", {}),
  p("INS-ALT", "Altimeter (Kollsman)", "instruments", "system", "Aneroid, 3-1/8 in",
    "Three-pointer, baro set in inHg. Static source.", {}),
  p("INS-TC", "Turn coordinator / turn-and-bank", "instruments", "system", "Electric or vacuum",
    "Needle-ball or turn coordinator plus inclinometer. Standard-rate 3°/s.", {}),
  p("INS-HI", "Directional gyro (heading)", "instruments", "system", "Vacuum gyro",
    "Must be reset to the magnetic compass every 15 min — no slaving on the basic 172E.", {}),
  p("INS-VSI", "Vertical-speed indicator", "instruments", "system", "Static, 3-1/8 in",
    "Calibrated leak. Typical ±2,000 fpm face.", {}),
  p("INS-TACH", "Recording tachometer", "instruments", "system", "Mechanical / magnetic",
    "Flexible shaft from the engine. Hour meter is the Hobbs alternative on some ships.", { connections: [c("ENG-CRANKCASE", "cable", "Tach shaft")] }),
  p("INS-OIL", "Oil pressure & temperature", "instruments", "system", "Bourdon / ratiometer",
    "Often a combined gauge. Pressure capillary from the case; temp bulb in the sump.", {}),
  p("INS-AMMETER", "Ammeter", "instruments", "system", "Shunt-type",
    "Charge/discharge of the generator. Zero in cruise with a healthy system is a later-alternator habit — generators often show a small charge.", {}),
  p("INS-FUEL-G", "Fuel quantity gauges", "instruments", "system", "Float sender, 12 V",
    "One per tank. BOTH does not sum — read each. Unreliable at the bottom: visual check is required.",
    { connections: [c("FUEL-TANK-L", "cable", "Left sender"), c("FUEL-TANK-R", "cable", "Right sender")] }),
  p("INS-SUCTION", "Suction gauge", "instruments", "system", "Vacuum",
    "Gyro vacuum, typically 4.6–5.4 inHg. Pump on the accessory case.", {}),
  p("INS-COMPASS", "Magnetic compass", "instruments", "system", "Wet compass, alcohol",
    "On the glare shield / windshield bow. Swung after radio or panel work.", {}),
  p("INS-NAVCOM", "Narco / King NAV-COM (Skyhawk)", "instruments", "system", "Tube/early solid-state",
    "Center-stack NAV/COM typical of a 1964 Skyhawk: Narco Mark 12 or King KX-series, with a separate omni indicator. Not standard on the stripper 172.", {}),
  p("INS-CLOCK", "Panel clock", "instruments", "system", "Mechanical or 12 V",
    "8-day wind or electric. Required for IFR time.", {}),

  // ——— Interior ———
  p("INT-SEAT-FL", "Pilot seat", "interior", "interior", "Steel frame, vinyl, foam",
    "Adjustable fore-aft (six-way optional from 172C). Lap belt; shoulder harness was not yet standard in 1964.",
    { weightLb: 18, finish: "Red or beige vinyl" }),
  p("INT-SEAT-FR", "Copilot seat", "interior", "interior", "Steel frame, vinyl, foam",
    "Matching right front seat.", { weightLb: 18 }),
  p("INT-SEAT-REAR", "Rear bench seat", "interior", "interior", "Steel frame, vinyl",
    "Two-place bench. Folding hat shelf behind (172D). Optional child seat in baggage on 172C+.",
    { weightLb: 16 }),
  p("INT-GLARESHIELD", "Glare shield", "interior", "interior", "Padded vinyl over aluminum",
    "Anti-glare brow over the panel. Compass often sits on top.", {}),
  p("INT-HAT-SHELF", "Folding hat shelf", "interior", "interior", "Plywood / vinyl",
    "172D folding shelf in the rear cabin, just forward of Omni-Vision glass.", { connections: [c("FUS-BULKHEAD-FS110", "hinge", "Shelf")] }),
  p("INT-YOKES-BOOT", "Column boots", "interior", "interior", "Vinyl",
    "Close the column slots in the panel.", {}),

  // ——— Cowling ———
  p("CWL-LEFT", "Left cowl half", "cowling", "fairing", "2024-T3 / 6061, 0.025",
    "Two-piece split cowling, camlocks (Dzus-style) along the split and firewall. Cooling inlet in the nose bowl.",
    { connections: [c("FUS-FIREWALL", "clamp", "Camlocks / hinges"), c("CWL-RIGHT", "clamp", "Center split")] }),
  p("CWL-RIGHT", "Right cowl half", "cowling", "fairing", "2024-T3 / 6061, 0.025",
    "Matching right half. Oil door on some Skyhawks; otherwise dipstick under the cowl.", {}),
  p("CWL-NOSE", "Nose bowl & inlets", "cowling", "fairing", "Aluminum / fiberglass",
    "172B reshaped cowl with pointed spinner. Two cooling inlets feed the baffled O-300. Exhaust exits under the rear cowl.", {}),
  p("CWL-ANTIGLARE", "Cowl anti-glare deck", "cowling", "fairing", "Flat black enamel",
    "Flat black on the cowl top between spinner and windshield — keeps the spinner glint out of the pilot's eyes.", {}),
];

export const PARTS_BY_ID: Record<string, Part> = Object.fromEntries(PARTS.map((x) => [x.id, x]));

export function resolvePart(id: string): Part {
  const found = PARTS_BY_ID[id];
  if (found) return found;
  const prefix = id.split("-")[0];
  const systemMap: Record<string, SystemId> = {
    FUS: "fuselage",
    WING: "wing",
    EMP: "empennage",
    GEAR: "landing-gear",
    ENG: "powerplant",
    PROP: "propeller",
    CTL: "flight-controls",
    FUEL: "fuel",
    ELE: "electrical",
    INS: "instruments",
    INT: "interior",
    CWL: "cowling",
  };
  return p(
    id,
    id.replace(/-/g, " ").toLowerCase().replace(/\b\w/g, (c) => c.toUpperCase()),
    systemMap[prefix ?? ""] ?? "fuselage",
    "structure",
    "2024-T3",
    "Sub-component of the 172E reconstruction.",
    { source: "SM-100" },
  );
}

export function partsForSystem(system: SystemId): Part[] {
  return PARTS.filter((p) => p.system === system);
}

export const PART_COUNT = PARTS.length;
export const SYSTEM_COUNT = new Set(PARTS.map((p) => p.system)).size;
